Repository kubernetes-sigs/prow, pull requests merged in 2024-11, with the labels that each got.

#316 Revert "`deck`: don't serve the ready endpoint until immediately prior to starting the server"
  cmd/deck/main.go
  test/integration/config/prow/cluster/deck_tenant_deployment.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#298 Update code-generator to 1.30.1
  config/prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
  hack/make-rules/update/codegen.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/typed/prowjobs/v1/fake/fake_prowjob.go
  pkg/client/clientset/versioned/typed/prowjobs/v1/prowjobs_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/pipeline/clientset/versioned/clientset.go
  pkg/pipeline/clientset/versioned/fake/clientset_generated.go
  pkg/pipeline/clientset/versioned/typed/pipeline/v1/fake/fake_pipeline.go
  pkg/pipeline/clientset/versioned/typed/pipeline/v1/fake/fake_pipelinerun.go
  pkg/pipeline/clientset/versioned/typed/pipeline/v1/fake/fake_task.go
  pkg/pipeline/clientset/versioned/typed/pipeline/v1/fake/fake_taskrun.go
  pkg/pipeline/clientset/versioned/typed/pipeline/v1/pipeline_client.go
  pkg/pipeline/informers/externalversions/factory.go
  pkg/spyglass/lenses/common/bindata.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#317 `deck`: move readiness serve to where we actually start the server
  cmd/deck/main.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#323 trigger: improve experience of guided comment
  pkg/pjutil/help.go
  pkg/plugins/trigger/generic-comment_test.go
Labels: cncf-cla: yes, ok-to-test, approved, size/S, lgtm

#326 fix: respect s3 custom endpoint config in aws sdk
  go.mod
  pkg/io/providers/aws.go
  pkg/io/providers/aws_test.go
Labels: cncf-cla: yes, ok-to-test, approved, size/L, lgtm
