Repository kubernetes-sigs/prow, pull requests merged in 2024-05, with the labels that each got.

#141 chore: replace issue link to kubernetes-sigs/prow repo
  pkg/github/report/report_test.go
  pkg/plugins/bugzilla/bugzilla_test.go
  pkg/plugins/dco/dco_test.go
  pkg/plugins/invalidcommitmsg/invalidcommitmsg_test.go
  pkg/plugins/respond.go
  pkg/plugins/retitle/retitle_test.go
Labels: cncf-cla: yes, ok-to-test, approved, size/L, lgtm

#103 doc: Update outdated hyperlinks in website
  cmd/checkconfig/main.go
  cmd/checkconfig/main_test.go
  cmd/deck/main.go
  cmd/deck/static/common/rerun.ts
  pkg/flagutil/github.go
  pkg/flagutil/storage.go
  pkg/genfiles/genfiles_test.go
  pkg/plugins/approve/approve.go
  pkg/plugins/config.go
  pkg/plugins/plugin-config-documented.yaml
  site/content/en/_index.html
  site/content/en/docs/announcements.md
  site/content/en/docs/build-clusters.md
  site/content/en/docs/build-test-update.md
  site/content/en/docs/components/_index.md
  site/content/en/docs/components/cli-tools/generic-autobumper.md
  site/content/en/docs/components/cli-tools/peribolos.md
  site/content/en/docs/components/cli-tools/phony.md
  site/content/en/docs/components/core/crier.md
  site/content/en/docs/components/core/deck/_index.md
  site/content/en/docs/components/core/deck/github-oauth-setup.md
  site/content/en/docs/components/core/prow-controller-manager.md
  site/content/en/docs/components/core/tide/config.md
  site/content/en/docs/components/deprecated/phaino.md
  site/content/en/docs/components/optional/branchprotector.md
  site/content/en/docs/components/optional/exporter.md
  site/content/en/docs/components/optional/gangway.md
  site/content/en/docs/components/optional/status-reconciler.md
  site/content/en/docs/components/optional/sub.md
  site/content/en/docs/components/plugins/_index.md
  site/content/en/docs/components/plugins/approve/approvers/_index.md
  site/content/en/docs/components/pod-utilities/_index.md
  site/content/en/docs/config.md
  site/content/en/docs/gerrit.md
  site/content/en/docs/getting-started-deploy.md
  site/content/en/docs/getting-started-develop.md
  site/content/en/docs/github.md
  site/content/en/docs/jobs.md
  site/content/en/docs/life-of-a-prow-job.md
  site/content/en/docs/metadata-artifacts.md
  site/content/en/docs/metrics/_index.md
  site/content/en/docs/more-prow.md
  site/content/en/docs/overview/_index.md
  site/content/en/docs/prow-secrets.md
  site/content/en/docs/scaling.md
  site/content/en/docs/spyglass/_index.md
  site/content/en/docs/spyglass/architecture.md
  site/content/en/docs/spyglass/write-a-lens.md
  site/content/en/docs/test/integration/_index.md
  site/content/en/docs/test/integration/fakegitserver.md
Labels: cncf-cla: yes, tide/merge-method-squash, ok-to-test, approved, size/L, lgtm

#129 Update to controller-runtime v0.16.5
  cmd/crier/main.go
  cmd/deck/main.go
  cmd/horologium/main.go
  cmd/pipeline/controller.go
  cmd/prow-controller-manager/main.go
  cmd/sinker/main.go
  cmd/sinker/main_test.go
  cmd/tide/main.go
  config/prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
  go.mod
  go.sum
  pkg/config/prow-config-documented.yaml
  pkg/crier/reporters/criercommonlib/updatereportstatus.go
  pkg/flagutil/kubernetes_cluster_clients.go
  pkg/gangway/client/common.go
  pkg/googlecloudbuild/client/client.go
  pkg/logrusutil/logrusutil.go
  pkg/moonraker/client.go
  pkg/plank/controller_test.go
  pkg/plank/reconciler.go
  pkg/plank/reconciler_test.go
  pkg/plugins/trigger/trigger.go
  pkg/resultstore/writer/writer.go
  pkg/testutil/fake_manager.go
  pkg/tide/status_test.go
  pkg/tide/tide.go
  pkg/tide/tide_test.go
  test/integration/test/crier_test.go
  test/integration/test/deck_test.go
  test/integration/test/gerrit_test.go
  test/integration/test/hook_test.go
  test/integration/test/horologium_test.go
  test/integration/test/pod-utils_test.go
  test/integration/test/setup.go
  test/integration/test/sinker_test.go
  test/integration/test/sub_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#148 Organize `.gitignore`
  .gitignore
Labels: cncf-cla: yes, tide/merge-method-squash, approved, size/M, lgtm

#123 build images using cloudbuild
  README.md
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#116 `gangway`: add status change endpoint
  pkg/gangway/gangway.go
  pkg/gangway/gangway.pb.go
  pkg/gangway/gangway.proto
  pkg/gangway/gangway_api_descriptor.pb
  pkg/gangway/gangway_grpc.pb.go
  test/integration/config/prow/cluster/gangway_rbac.yaml
  test/integration/config/prow/jobs/periodics.yaml
  test/integration/config/prow/jobs/postsubmits.yaml
  test/integration/test/gangway_test.go
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XXL

#156 Revert "`gangway`: add status change endpoint"
  pkg/gangway/gangway.go
  pkg/gangway/gangway.pb.go
  pkg/gangway/gangway.proto
  pkg/gangway/gangway_api_descriptor.pb
  pkg/gangway/gangway_grpc.pb.go
  test/integration/config/prow/cluster/gangway_rbac.yaml
  test/integration/config/prow/jobs/periodics.yaml
  test/integration/config/prow/jobs/postsubmits.yaml
  test/integration/test/gangway_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#155 fix typo in serviceaccount format
  cloudbuild.yaml
Labels: cncf-cla: yes, approved, lgtm, size/XS

#166 nit: Update Node version and dependencies
  hack/run-in-node-container.sh
  package.json
Labels: cncf-cla: yes, tide/merge-method-squash, approved, kind/cleanup, size/S, lgtm

#164 [Feature]: [assign plugin] Support GitHub Organization Teams as targets for assign/cc commands
  pkg/plugins/assign/assign.go
  pkg/plugins/assign/assign_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, approved, size/M, lgtm

#168 Doc: Write PluginHelp in assign.go
  pkg/plugins/assign/assign.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#167 nit: Update Go version
  go.mod
  hack/tools/go.mod
Labels: cncf-cla: yes, approved, kind/cleanup, lgtm, size/XS

#170 plugins/OWNERS: expand contribex TL alias
  pkg/plugins/OWNERS
Labels: cncf-cla: yes, approved, sig/contributor-experience, lgtm, size/XS

#171 Fixed typo
  site/content/en/docs/life-of-a-prow-job.md
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XS

#174 external-plugins/cherrypicker: include PR description as comment
  cmd/external-plugins/cherrypicker/server.go
  cmd/external-plugins/cherrypicker/server_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#159 Revert "Revert "`gangway`: add status change endpoint""
  pkg/gangway/client/common.go
  pkg/gangway/gangway.go
  pkg/gangway/gangway.pb.go
  pkg/gangway/gangway.proto
  pkg/gangway/gangway_api_descriptor.pb
  pkg/gangway/gangway_grpc.pb.go
  test/integration/config/prow/cluster/gangway_rbac.yaml
  test/integration/config/prow/jobs/periodics.yaml
  test/integration/config/prow/jobs/postsubmits.yaml
  test/integration/test/gangway_test.go
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XXL
