Repository kubernetes-sigs/prow, pull requests merged in 2024-12, with the labels that each got.

#335 install kind for integration tests
  hack/tools/ensure-kind.sh
  test/integration/integration-test.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#333 Added a plan struct inside organization
  pkg/github/types.go
Labels: cncf-cla: yes, ok-to-test, approved, size/S, lgtm

#338 `deck`: "/log" endpoint should not show `hidden` jobs if deck isn't configured to allow `hidden`
  pkg/deck/jobs/jobs.go
  pkg/deck/jobs/jobs_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#331 Allow Passing AWS Session Token
  pkg/io/providers/aws.go
  pkg/io/providers/providers.go
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XS

#336 add `smg247` as `Prow` approver
  OWNERS
Labels: cncf-cla: yes, approved, lgtm, size/XS

#341 MinIO for Azure deprecation deployment warning + pinning LKG release
  site/content/en/docs/getting-started-deploy.md
Labels: cncf-cla: yes, approved, size/S, lgtm

#342 Genericize Code Review Link Title
  pkg/plugins/approve/approve_test.go
  pkg/plugins/approve/approvers/approvers_test.go
  pkg/plugins/approve/approvers/owners.go
Labels: cncf-cla: yes, ok-to-test, approved, size/M, lgtm

#346 Respect newline in command examples in command-help
  cmd/deck/static/style.css
Labels: cncf-cla: yes, approved, lgtm, size/XS

#351 Move some approvers to emeritus.
  OWNERS
Labels: cncf-cla: yes, approved, size/S, lgtm

#350 Upgrade golang v1.23
  .go-version
  cmd/checkconfig/main.go
  cmd/peribolos/main.go
  go.mod
  hack/gen-prow-documented/main.go
  hack/gen-prow-documented/main_test.go
  hack/tools/go.mod
  hack/tools/go.sum
  netlify.toml
  pkg/bugzilla/client.go
  pkg/config/tide.go
  pkg/crier/reporters/gerrit/reporter_test.go
  pkg/genyaml/genyaml.go
  pkg/genyaml/genyaml_test.go
  pkg/gerrit/adapter/adapter_test.go
  pkg/githuboauth/githuboauth.go
  pkg/jenkins/jenkins.go
  pkg/netlify.toml
  pkg/plugins/golint/golint_test.go
  pkg/plugins/heart/heart.go
  pkg/plugins/plugins.go
  site/go.mod
  site/go.sum
  site/package-lock.json
Labels: cncf-cla: yes, tide/merge-method-squash, approved, lgtm, size/XXL
