Repository kubernetes-sigs/prow, pull requests merged in 2024-03, with the labels that each got.

#87 Add assorted files from kubernetes/test-infra that are needed to build and test.
  .golangci.yml
  .ko.yaml
  Makefile
  hack/make-rules/go-run/arbitrary.sh
  hack/make-rules/update/codegen.sh
  hack/make-rules/update/file-perms.sh
  hack/make-rules/update/go-deps.sh
  hack/make-rules/update/gofmt.sh
  hack/make-rules/update/misspell.sh
  hack/make-rules/update/ts-rollup.sh
  hack/make-rules/verify/all.sh
  hack/make-rules/verify/boilerplate.sh
  hack/make-rules/verify/file-perms.sh
  hack/make-rules/verify/go-deps.sh
  hack/make-rules/verify/gofmt.sh
  hack/make-rules/verify/golangci-lint.sh
  hack/make-rules/verify/misspell.sh
  hack/make-rules/verify/yamllint.sh
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#88 Update sync-prow.sh script to sync all needed code and handle the module rename.
  hack/scripts/sync-prow.sh
Labels: cncf-cla: yes, approved, size/M, lgtm

#89 Fix spelling check to actually return an error.
  .gitignore
  hack/make-rules/update/misspell.sh
  hack/make-rules/verify/misspell.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#93 Remove non-prow images in .ko.yaml file.
  .ko.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#92 Add missing build dependencies from test-infra for deck image build
  hack/build/ensure-node_modules.sh
  hack/run-in-node-container.sh
  hack/ts.rollup_bundle.min.minify_options.json
  package.json
  rollup.config.js
  tsconfig.json
Labels: cncf-cla: yes, approved, size/L, lgtm

#96 Prevent sync-prow.sh from clobbering itself.
  hack/scripts/sync-prow.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS

#97 Minor fixes to sync-prow.sh.
  hack/scripts/sync-prow.sh
Labels: cncf-cla: yes, approved, lgtm, size/XS
