Repository kubernetes-sigs/prow, pull requests merged in 2024-07, with the labels that each got.

#196 Don't embed tekton schema in ProwJob CRD
  cmd/admission/admission.go
  cmd/admission/dev.yaml
  cmd/deck/main.go
  config/prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
  pkg/apis/prowjobs/v1/types.go
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XXL

#207 Bump git-custom-k8s-auth image
  .ko.yaml
Labels: cncf-cla: yes, approved, size/S, lgtm

#203 gangway: BulkJobStatusChange: return early and finish later
  pkg/gangway/gangway.go
  pkg/gangway/gangway.pb.go
  pkg/gangway/gangway.proto
  pkg/gangway/gangway_api_descriptor.pb
  pkg/gangway/gangway_grpc.pb.go
  test/integration/test/gangway_test.go
Labels: cncf-cla: yes, ok-to-test, approved, size/XL, lgtm

#211 Use k8s-staging-test-infra images for base images.
  .ko.yaml
Labels: cncf-cla: yes, approved, size/M, lgtm

#213 Move Travis and Mitchel to emeritus.
  cmd/deck/OWNERS
  cmd/generic-autobumper/OWNERS
  pkg/deck/OWNERS
  pkg/genyaml/OWNERS
  pkg/spyglass/OWNERS
Labels: cncf-cla: yes, approved, size/S, lgtm
