Repository kubernetes-sigs/prow, pull requests merged in 2024-01, with the labels that each got.

#72 fixes for sub
  site/content/en/docs/components/optional/sub.md
Labels: cncf-cla: yes, approved, size/L, lgtm

#73 Add codegen related tools and scripts
  .go-version
  config/prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
  go.mod
  go.sum
  hack/boilerplate/boilerplate.generated.go.txt
  hack/build/setup-go.sh
  hack/gen-prow-documented/main.go
  hack/gen-prow-documented/main_test.go
  hack/make-rules/update/codegen.sh
  hack/make-rules/verify/codegen.sh
  hack/third_party/gimme/LICENSE
  hack/third_party/gimme/README.md
  hack/third_party/gimme/gimme
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#78 Add script to sync Prow commits from test-infra repo
  hack/scripts/sync-prow.sh
Labels: cncf-cla: yes, approved, size/M, lgtm

#79 Sync Prow commits from the test-infra repo
  prow/apis/prowjobs/v1/types.go
  prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  prow/cmd/checkconfig/main_test.go
  prow/cmd/sinker/main.go
  prow/cmd/sinker/main_test.go
  prow/config/config.go
  prow/config/config_test.go
  prow/config/prow-config-documented.yaml
  prow/crier/controller.go
  prow/crier/reporters/gcs/reporter.go
  prow/crier/reporters/gcs/util/util.go
  prow/crier/reporters/resultstore/reporter.go
  prow/crier/reporters/resultstore/reporter_test.go
  prow/pjutil/pjutil.go
  prow/pjutil/pjutil_test.go
  prow/plank/reconciler.go
  prow/pod-utils/clone/clone.go
  prow/pod-utils/clone/clone_test.go
  prow/resultstore/uploader.go
  prow/resultstore/writer/writer.go
  prow/tide/github.go
Labels: cncf-cla: yes, approved, size/XL, lgtm

#81 Revert "Add go.mod file"
  prow/go.mod
  prow/go.sum
Labels: cncf-cla: yes, approved, lgtm, size/XXL

#83 Add missing Go module in go.mod
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/S, lgtm
