Repository kubernetes-sigs/prow, pull requests merged in 2024-04, with the labels that each got.

#99 Update README to reflect the source code migration.
  README.md
Labels: cncf-cla: yes, approved, lgtm, size/XS

#100 Make image consistency errors more actionable.
  prow/cmd/generic-autobumper/main.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#104 add droslean in the OWNERS file
  OWNERS
Labels: cncf-cla: yes, approved, lgtm, size/XS

#107 docs: Migrate ghProxy docs to Prow website
  ghproxy/README.md
  ghproxy/ghcache/README.md
  ghproxy/throttling-algorithm.md
  site/content/en/docs/ghproxy/_index.md
  site/content/en/docs/ghproxy/ghcache.md
  site/content/en/docs/ghproxy/throttling-algorithm.md
Labels: cncf-cla: yes, tide/merge-method-squash, ok-to-test, approved, size/L, lgtm

#112 Include cluster name in authorization error messages
  pkg/flagutil/kubernetes_cluster_clients.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#114 OWNERS: move listx to emeritus status
  OWNERS
  cmd/sub/OWNERS
  pkg/pubsub/OWNERS
  test/integration/OWNERS
Labels: cncf-cla: yes, approved, size/S, lgtm

#106 chore: update deps for sigs.k8s.io/controller-runtime@v0.16.3 - step 1
  .gitignore
  go.mod
  go.sum
Labels: cncf-cla: yes, tide/merge-method-squash, ok-to-test, approved, size/M, lgtm

#120 doc: Update `cmd`, `pkg`, & `test` paths (follow-up of #101)
  site/content/en/docs/build-test-update.md
  site/content/en/docs/components/cli-tools/generic-autobumper.md
  site/content/en/docs/components/cli-tools/peribolos.md
  site/content/en/docs/components/cli-tools/phaino.md
  site/content/en/docs/components/cli-tools/phony.md
  site/content/en/docs/components/core/deck/_index.md
  site/content/en/docs/components/core/prow-controller-manager.md
  site/content/en/docs/components/deprecated/cm2kc.md
  site/content/en/docs/components/deprecated/plank.md
  site/content/en/docs/components/optional/branchprotector.md
  site/content/en/docs/components/optional/hmac.md
  site/content/en/docs/components/optional/tot/fallbackcheck.md
  site/content/en/docs/getting-started-deploy.md
  site/content/en/docs/spyglass/write-a-lens.md
  site/content/en/docs/test/integration/_index.md
Labels: cncf-cla: yes, ok-to-test, approved, size/L, lgtm

#127 Bump golangci-lint to v1.57.2
  .golangci.yml
  hack/make-rules/verify/golangci-lint.sh
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/git/v2/client_factory.go
  pkg/git/v2/interactor.go
  pkg/github/app_auth_roundtripper.go
  pkg/github/client.go
  pkg/github/client_test.go
  pkg/github/types.go
  pkg/githuboauth/githuboauth_test.go
  test/integration/internal/fakegitserver/fakegitserver.go
Labels: cncf-cla: yes, approved, size/XL, kind/cleanup, lgtm

#131 tide: consider `skipped` run conclusion as `success`
  pkg/tide/tide.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#122 [peribolos] only log caller when log level is raised
  cmd/peribolos/main.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#126 replace deprecated NewFakeClient with NewClientBuilder
  .golangci.yml
  cmd/sinker/main_test.go
  pkg/crier/controller_test.go
  pkg/crier/reporters/gerrit/reporter_test.go
  pkg/crier/reporters/github/reporter_test.go
  pkg/deck/jobs/jobs_test.go
  pkg/pjutil/abort_test.go
  pkg/plank/controller_test.go
  pkg/plank/reconciler_test.go
  pkg/tide/gerrit_test.go
  pkg/tide/status_test.go
  pkg/tide/tide_test.go
Labels: cncf-cla: yes, approved, kind/cleanup, size/L, lgtm

#124 Remove deprecated GitHub client functions
  pkg/github/client.go
  pkg/github/client_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#136 external-plugins/cherrypicker: add support for branch chains
  cmd/external-plugins/cherrypicker/lib/lib.go
  cmd/external-plugins/cherrypicker/server.go
  cmd/external-plugins/cherrypicker/server_test.go
  pkg/plugins/bugzilla/bugzilla_test.go
Labels: cncf-cla: yes, approved, size/M, lgtm
