Repository kubernetes-sigs/prow, pull requests merged in 2024-06, with the labels that each got.

#184 Use Cluster and not Manager for build clusters
  cmd/prow-controller-manager/main.go
  cmd/sinker/main.go
  pkg/flagutil/kubernetes_cluster_clients.go
  pkg/plank/reconciler.go
  pkg/plank/reconciler_test.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#189 cherrypicker: create comment for failed patch requests
  cmd/external-plugins/cherrypicker/server.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#149 nit: Add a missing period after 'The K8s Authors' string, in copyright strings
  site/config.toml
  test/integration/config/prow/cluster/crier_rbac.yaml
  test/integration/config/prow/cluster/deck_deployment.yaml
  test/integration/config/prow/cluster/deck_service.yaml
  test/integration/config/prow/cluster/deck_tenant_deployment.yaml
  test/integration/config/prow/cluster/hook_deployment.yaml
  test/integration/config/prow/cluster/hook_service.yaml
  test/integration/config/prow/cluster/horologium_deployment.yaml
  test/integration/config/prow/cluster/prow_controller_manager_deployment.yaml
  test/integration/config/prow/cluster/prow_controller_manager_rbac.yaml
  test/integration/config/prow/cluster/prow_controller_manager_service.yaml
  test/integration/config/prow/cluster/sinker_service.yaml
  test/integration/config/prow/cluster/tide_deployment.yaml
  test/integration/config/prow/cluster/tide_service.yaml
  test/integration/config/prow/cluster/webhook_server_deployment.yaml
  test/integration/config/prow/cluster/webhook_server_service.yaml
Labels: cncf-cla: yes, tide/merge-method-squash, approved, size/M, lgtm

#144 branchprotector: add support for SIGTERM/SIGINT catching
  cmd/branchprotector/protect.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#188 feat(pkg/plugins/dco): ignore merged type commits
  pkg/plugins/dco/dco.go
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XS

#197 GitHub: Add ListTags method
  pkg/github/client.go
  pkg/github/types.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#198 gangway: add nil check on refs
  pkg/gangway/gangway.go
  test/integration/test/gangway_test.go
Labels: cncf-cla: yes, ok-to-test, approved, size/S, lgtm

#200 Update github.com/prometheus/common module
  go.mod
  go.sum
  pkg/metrics/push.go
Labels: cncf-cla: yes, approved, size/L, lgtm
