Repository kubernetes-sigs/prow, pull requests merged in 2025-04, with the labels that each got.

#416 Support retriggering complex workflows
  pkg/github/client.go
  pkg/github/client_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#379 Using material design for other tables as well
  cmd/deck/static/common/common.ts
  cmd/deck/static/prow/prow.ts
  cmd/deck/static/style.css
  cmd/deck/template/base.html
  cmd/deck/template/index.html
  cmd/deck/template/tide-history.html
  cmd/deck/template/tide.html
Labels: cncf-cla: yes, ok-to-test, approved, size/M, lgtm, area/deck

#432 Fix issue with help, triggered by code block
  pkg/markdown/code_block.go
  pkg/markdown/code_block_test.go
  pkg/plugins/plugin-config-documented.yaml
  pkg/plugins/trigger/generic-comment.go
  pkg/plugins/trigger/generic-comment_test.go
  pkg/spyglass/lenses/common/bindata.go
Labels: cncf-cla: yes, approved, size/L, lgtm, area/plugins, area/spyglass

#412 Consolidate revival logic in case pod is in an unknown, evicted or unreachable state, limit the number of revivals to 3
  config/prow/cluster/prowjob-crd/prowjob_customresourcedefinition.yaml
  pkg/apis/prowjobs/v1/types.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/prow-config-documented.yaml
  pkg/plank/controller_test.go
  pkg/plank/reconciler.go
Labels: cncf-cla: yes, approved, size/L, lgtm, area/prowcm, area/spyglass

#434 Update google.golang.org/grpc to v1.72.0
  go.mod
  go.sum
Labels: cncf-cla: yes, ok-to-test, approved, size/M, lgtm

#435 chore(pkg/statusreconciler): update code comment on presubmit filter behavior
  pkg/statusreconciler/controller.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, lgtm, size/XS, area/status-reconciler

#441 Adding the ability to specify a custom backoff
  pkg/flagutil/jira.go
  pkg/jira/jira.go
Labels: cncf-cla: yes, ok-to-test, approved, size/M, lgtm

#442 Properly set default values
  pkg/jira/jira.go
Labels: cncf-cla: yes, approved, size/S, needs-ok-to-test, lgtm
