Repository kubernetes-sigs/prow, pull requests merged in 2025-02, with the labels that each got.

#296 (spyglass/lenses) allow configuration sandbox permissions
  cmd/checkconfig/testdata/combined.yaml
  cmd/deck/template/spyglass.html
  pkg/spyglass/lenses/buildlog/lens.go
  pkg/spyglass/lenses/buildlog/lens_test.go
Labels: cncf-cla: yes, ok-to-test, approved, size/M, lgtm

#367 fix(status-reconciler): correctly run run_if_changed presubmits
  pkg/statusreconciler/controller.go
  pkg/statusreconciler/controller_test.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/M, lgtm

#358 Config to automatically Re-trigger failed periodics
  cmd/horologium/main.go
  cmd/horologium/main_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/jobs.go
  pkg/kube/prowjob.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#371 Revert "(spyglass/lenses) allow configuration sandbox permissions"
  cmd/checkconfig/testdata/combined.yaml
  cmd/deck/template/spyglass.html
  pkg/spyglass/lenses/buildlog/lens.go
  pkg/spyglass/lenses/buildlog/lens_test.go
Labels: cncf-cla: yes, approved, size/M, lgtm

#375 deps: bump golang.org/x/*
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/M, lgtm

#377 Change behaviour of RunAll strategy in horologium
  cmd/horologium/main.go
  cmd/horologium/main_test.go
  pkg/config/jobs.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#368 Handle empty alias group case
  pkg/plugins/verify-owners/verify-owners_test.go
  pkg/repoowners/repoowners.go
  pkg/repoowners/repoowners_test.go
Labels: cncf-cla: yes, ok-to-test, approved, size/L, lgtm

#381 Revert "Handle empty alias group case"
  pkg/plugins/verify-owners/verify-owners_test.go
  pkg/repoowners/repoowners.go
  pkg/repoowners/repoowners_test.go
Labels: cncf-cla: yes, approved, size/L, lgtm

#383 Fix `sinker's` flaky integration test
  test/integration/test/sinker_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XS

#385 fix error shadowing in `sinker` integration test
  test/integration/test/sinker_test.go
Labels: cncf-cla: yes, approved, lgtm, size/XS
