Repository kubernetes-sigs/prow, pull requests merged in 2025-03, with the labels that each got.

#387 `sinker` integration test: always wait 1 minute to check for pod deletion
  test/integration/test/sinker_test.go
Labels: cncf-cla: yes, tide/merge-method-squash, approved, size/M, lgtm

#382 Do not suggest author when require_self_approve is true.
  pkg/plugins/approve/approve.go
  pkg/plugins/approve/approve_test.go
  pkg/plugins/approve/approvers/approvers_test.go
Labels: cncf-cla: yes, ok-to-test, approved, size/L, lgtm

#395 Update label assignments in OWNERS files to labels migrated from k/test-infra
  cmd/branchprotector/OWNERS
  cmd/clonerefs/OWNERS
  cmd/config-bootstrapper/OWNERS
  cmd/crier/OWNERS
  cmd/deck/OWNERS
  cmd/entrypoint/OWNERS
  cmd/gangway/OWNERS
  cmd/gcsupload/OWNERS
  cmd/generic-autobumper/OWNERS
  cmd/gerrit/OWNERS
  cmd/hmac/OWNERS
  cmd/hook/OWNERS
  cmd/horologium/OWNERS
  cmd/initupload/OWNERS
  cmd/jenkins-operator/OWNERS
  cmd/mkpod/OWNERS
  cmd/moonraker/OWNERS
  cmd/peribolos/OWNERS
  cmd/prow-controller-manager/OWNERS
  cmd/sidecar/OWNERS
  cmd/sinker/OWNERS
  cmd/status-reconciler/OWNERS
  cmd/sub/OWNERS
  cmd/tide/OWNERS
  pkg/clonerefs/OWNERS
  pkg/crier/OWNERS
  pkg/deck/OWNERS
  pkg/entrypoint/OWNERS
  pkg/gangway/OWNERS
  pkg/gcsupload/OWNERS
  pkg/gerrit/OWNERS
  pkg/hook/OWNERS
  pkg/initupload/OWNERS
  pkg/jenkins/OWNERS
  pkg/moonraker/OWNERS
  pkg/plank/OWNERS
  pkg/plugins/OWNERS
  pkg/pod-utils/OWNERS
  pkg/pubsub/OWNERS
  pkg/sidecar/OWNERS
  pkg/spyglass/OWNERS
  pkg/statusreconciler/OWNERS
  pkg/tide/OWNERS
Labels: cncf-cla: yes, ok-to-test, approved, size/M, lgtm

#402 eliminate unused node_module caching attempt
  hack/build/ensure-node_modules.sh
Labels: cncf-cla: yes, approved, size/S, lgtm

#398 Fix WaitForStatus comment to use the correct field name
  pkg/plugins/config.go
Labels: cncf-cla: yes, ok-to-test, approved, lgtm, size/XS, area/plugins

#403 ci: remove python dep installation
  Makefile
  hack/run-in-python-container.sh
  requirements3.txt
Labels: cncf-cla: yes, approved, size/S, lgtm

#405 deps: bump github.com/go-git/go-git/v5
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/L, lgtm

#407 Add more job information to GetJobExecution
  pkg/gangway/gangway.go
  pkg/gangway/gangway.pb.go
  pkg/gangway/gangway.proto
  pkg/gangway/gangway_api_descriptor.pb
Labels: cncf-cla: yes, ok-to-test, approved, size/L, lgtm, area/gangway

#411 deps(hack/tools): bump & cleanup
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: cncf-cla: yes, approved, size/XL, lgtm
